# Generated by Django 4.1.2 on 2022-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ManyToManyField(blank=True, to='store.image', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='фото'),
        ),
    ]
