# Generated by Django 4.1.2 on 2022-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_image_alter_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('name', 'image'), 'verbose_name': 'фото', 'verbose_name_plural': 'фото'},
        ),
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='главное фото'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='photos', to='store.image', verbose_name='фото'),
        ),
    ]
